FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/platform-api/package*.json ./apps/platform-api/
COPY apps/platform-web/package*.json ./apps/platform-web/
RUN npm install
COPY . .
RUN npx prisma generate --schema=src/database/prisma/schema.prisma
RUN npm run build:frontend && npm run build:backend
EXPOSE 8080
CMD ["npm", "run", "dev:backend"]